### ISSUE TITLE
While running below command i am gettiog an error

### ISSUE THREAD

**Issue by Gajuharale** [fermi-lat/ScienceTools#10]
$conda build -c conda-forge -c fermi .
Traceback (most recent call last):
  File "/home/gajanan/anaconda3/envs/dev/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/gajanan/anaconda3/envs/dev/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/home/gajanan/anaconda3/envs/dev/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 472, in execute
    verify=args.verify, variants=args.variants, cache_dir=args.cache_dir)
  File "/home/gajanan/anaconda3/envs/dev/lib/python3.7/site-packages/conda_build/api.py", line 184, in build
    raise ValueError('No valid recipes found for input: {}'.format(recipe_paths_or_metadata))
ValueError: No valid recipes found for input: ['.']

Please help me

**Comment by donhorner** [comment]
Can I ask what your ultimate goal is here?  Based on this and the other issue you opened, you seem to be trying to compile the tools, which you should only need to do if you are trying to do software develop for them.

**Comment by Gajuharale** [comment]
I'm trying to connect to  fermitools and science tools.

https://github.com/fermi-lat/Fermitools-conda/wiki/Contributing-to-the-Fermitools#sciencetools-conda-recipe-contents

**Comment by donhorner** [comment]
I'm not sure what you mean.  If you just want to use the Fermitools, you don't need to compile them but just [install them with conda](https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions).  That's part of why we moved to conda to distribute them.  Also, the Fermitools and Science Tools are not separate things.  The Science Tools are just the old name for the software before we switch to using conda.

**Comment by Gajuharale** [comment]
Thank you for your clarification
The link I sent you, on that page it is given, I got confused.  Now you
clear my confusion.
Thank you
