### ISSUE TITLE
help with spacecraft pointing and exposure calculation code

### ISSUE THREAD

**Issue by nkelhos** [fermi-lat/ScienceTools#20]
This isn't really an issue so much as a help request, so I apologize if I've posted this in the wrong place.

My questions:

a) In the spacecraft file (the kind described here: https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Cicerone/Cicerone_Data/LAT_Data_Columns.html#SpacecraftFile) there are the columns RA_SCX, DEC_SCX, RA_SCZ, and DEC_SCZ for the directions of the satellite axes.  SCX is the direction of the satellite positive x axis.  Which axis (X+ or Z+) is towards the Front of the satellite, when calculating livetime cubes, exposure maps, and effective area?  I can't seem to find this anywhere.

To be specific, I'm looking for the 'θ = 0 degrees' direction in the "effective area vs θ" plot 
https://www.slac.stanford.edu/exp/glast/groups/canda/lat_Performance_files/gAeffTheta_10000_P8R3_SOURCE_V3fb_10MeV.png
which is from this page https://www.slac.stanford.edu/exp/glast/groups/canda/lat_Performance.htm

b) Where is the c++ code for gtltcube and gtexpmap stored on github?  I've searched for them, but can't seem to find them anywhere.  There's lots of code that runs gtltcube and gtexpmap on the command line, but I can't find the code for the binary itself.

Thanks for your help.

**Comment by nmirabal** [comment]
Answered via Fermi helpdesk. Closing.
