### ISSUE TITLE
Installation using CMAKE not finding helpix module

### ISSUE THREAD

**Issue by AnuvabAstro** [fermi-lat/ScienceTools#23]
Hi,
I am attempting to install ScienceTools in my local desktop (ubuntu 20.04) using the instruction set by creating the developer's environment and then using cmake to build the software, but I am running into an issue and the installation is breaking. Here are the steps I am following: 

**conda env create -n fermi-dev -f environments/fermitools-develop-linux.yml**
activating the environment: fermi_dev
**git submodule update --init .**
**cmake -S . -B RelWithDebInfo -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="/home/anuvab/analytical/observation/black_hole/ScienceTools" -DCMAKE_PREFIX_PATH="/home/anuvab/anaconda3/envs/fermi-dev"**

It is showing the following error:
**--   No package 'healpix_cxx' found
CMake Error at /home/anuvab/anaconda3/envs/fermi-dev/share/cmake-3.29/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - healpix_cxx

Call Stack (most recent call first):
  /home/anuvab/anaconda3/envs/fermi-dev/share/cmake-3.29/Modules/FindPkgConfig.cmake:847 (_pkg_check_modules_internal)
  CMakeLists.txt:45 (pkg_check_modules)**

However, in the original developer's environment (fermi_dev), I am finding the healpix package to be installed. Could you kindly let me know what is going wrong and how to circumvent this problem? Am I providing the correct path in DCMAKE_PREFIX_PATH? I am willing to provide further details if necessary.

regards,
Anuvab

**Comment by Areustle** [comment]
Hello Anuvab,

Unfortunately we cannot offer debugging support for local development environments, nor for source installs of the Sciencetools. 

Our supported and recommended method for using the Fermi Sciencetools is via the [Fermitools-conda](https://github.com/fermi-lat/Fermitools-conda/wiki/Quickstart-Guide) package.

If that is not sufficient, and you find that you need to compile the Sciencetools from source: I wish you the best of luck debugging your local environment.
